# Specify a base image
FROM node:16-alpine

#set the directory
WORKDIR /usr/app

# copy the package.jsoncontents
COPY ./package.json ./

# Install some depenendencies
RUN npm install

# copy all the contents..
COPY ./ ./

# Default command
CMD ["npm", "run", "start"]